# Generated by Django 4.2 on 2023-04-09 05:55

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=25, verbose_name='Зав. № машины')),
                ('motor_number', models.CharField(max_length=25, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(max_length=25, verbose_name='Зав. № трансмиссии')),
                ('bridge_drv_number', models.CharField(max_length=25, verbose_name='Зав. № ведущего моста')),
                ('bridge_ctrl_number', models.CharField(max_length=25, verbose_name='Зав. № управляемого моста')),
                ('contract', models.CharField(max_length=50, verbose_name='Договор поставки №, дата')),
                ('shipment', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=250, verbose_name='Грузополучатель (конечный потребитель)')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.IntegerField(choices=[(1, 'Модели техники'), (2, 'Модели двигателя'), (3, 'Модели трансмиссии'), (4, 'Модели ведущего моста'), (5, 'Модели управляемого моста'), (6, 'Виды ТО'), (7, 'Узлы'), (8, 'Способы восстановления'), (9, 'Организации, проводившие ТО')], verbose_name='Вид справочника')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата отказа')),
                ('mileage', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('repair_units', models.TextField(verbose_name='Используемые запасные части')),
                ('repair_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='app.machinery', verbose_name='Машина')),
                ('recovery', app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Способ восстановления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('unit', app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Узел отказа')),
            ],
            options={
                'verbose_name': 'Рекламации',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('mileage', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=15, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('form', app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Вид ТО')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='app.machinery', verbose_name='Машина')),
                ('organization', app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Организация, проводившая ТО')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
            },
        ),
        migrations.AddField(
            model_name='machinery',
            name='bridge_ctrl',
            field=app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='bridge_drv',
            field=app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='model',
            field=app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='motor',
            field=app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='transmission',
            field=app.models.ReferenceField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='Модель трансмиссии'),
        ),
    ]
